ALTER TABLE "DailyTopicPlan"
  ADD COLUMN IF NOT EXISTS "intervalMinMinutes" INTEGER NOT NULL DEFAULT 60,
  ADD COLUMN IF NOT EXISTS "intervalMaxMinutes" INTEGER NOT NULL DEFAULT 90,
  ADD COLUMN IF NOT EXISTS "windowStartHour" INTEGER NOT NULL DEFAULT 9,
  ADD COLUMN IF NOT EXISTS "windowEndHour" INTEGER NOT NULL DEFAULT 23,
  ADD COLUMN IF NOT EXISTS "weekdaysCsv" TEXT NOT NULL DEFAULT '1,2,3,4,5',
  ADD COLUMN IF NOT EXISTS "infoRatioPercent" INTEGER NOT NULL DEFAULT 70,
  ADD COLUMN IF NOT EXISTS "ctaRatioPercent" INTEGER NOT NULL DEFAULT 30,
  ADD COLUMN IF NOT EXISTS "telegramOnError" BOOLEAN NOT NULL DEFAULT true;

UPDATE "DailyTopicPlan"
SET
  "intervalMinMinutes" = COALESCE(NULLIF("intervalMinutes", 0), 60),
  "intervalMaxMinutes" = GREATEST(COALESCE(NULLIF("intervalMinutes", 0), 60), COALESCE("intervalMaxMinutes", 90));
