import { createCanvas, type SKRSContext2D } from "@napi-rs/canvas";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { ChartPanelData } from "@/lib/market/types";

const BG = "#0b1220";
const PANEL_BG = "#111a2c";
const PANEL_BORDER = "#1f314f";
const TEXT_PRIMARY = "#e5edff";
const TEXT_MUTED = "#9db0d8";
const POS = "#10b981";
const NEG = "#f43f5e";
const LINE = "#60a5fa";

function drawSeries(
  ctx: SKRSContext2D,
  points: number[],
  x: number,
  y: number,
  width: number,
  height: number
) {
  if (points.length < 2) return;
  const min = Math.min(...points);
  const max = Math.max(...points);
  const range = max - min || 1;

  ctx.beginPath();
  points.forEach((value, idx) => {
    const px = x + (idx / (points.length - 1)) * width;
    const py = y + height - ((value - min) / range) * height;
    if (idx === 0) ctx.moveTo(px, py);
    else ctx.lineTo(px, py);
  });
  ctx.strokeStyle = LINE;
  ctx.lineWidth = 2;
  ctx.stroke();
}

function drawPanel(
  ctx: SKRSContext2D,
  panel: ChartPanelData,
  x: number,
  y: number,
  width: number,
  height: number
) {
  const pct = Number.isFinite(panel.dailyPct) ? panel.dailyPct : 0;
  const pctText = `${pct >= 0 ? "+" : ""}${pct.toFixed(2)}%`;
  const pctColor = pct >= 0 ? POS : NEG;

  ctx.fillStyle = PANEL_BG;
  ctx.strokeStyle = PANEL_BORDER;
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.roundRect(x, y, width, height, 14);
  ctx.fill();
  ctx.stroke();

  ctx.fillStyle = TEXT_PRIMARY;
  ctx.font = "bold 22px Arial";
  ctx.fillText(panel.label, x + 16, y + 34);

  ctx.fillStyle = TEXT_MUTED;
  ctx.font = "15px Arial";
  ctx.fillText("현재", x + 16, y + 58);

  ctx.fillStyle = TEXT_PRIMARY;
  ctx.font = "bold 24px Arial";
  ctx.fillText(panel.current.toLocaleString(), x + 16, y + 88);

  ctx.fillStyle = pctColor;
  ctx.font = "bold 18px Arial";
  ctx.fillText(`일간 ${pctText}`, x + width - 130, y + 34);

  drawSeries(ctx, panel.series, x + 16, y + 110, width - 32, height - 130);

  ctx.fillStyle = TEXT_MUTED;
  ctx.font = "12px Arial";
  ctx.fillText("7D", x + 16, y + height - 12);
}

export function renderDailySnapshot4Pack(panels: ChartPanelData[], asofDate: string) {
  if (panels.length !== 4) {
    throw new Error(`daily_snapshot_4pack requires 4 panels, got ${panels.length}`);
  }

  const width = 1400;
  const height = 900;
  const canvas = createCanvas(width, height);
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("Canvas 2d context unavailable");

  ctx.fillStyle = BG;
  ctx.fillRect(0, 0, width, height);

  ctx.fillStyle = "#d9e4ff";
  ctx.font = "bold 30px Arial";
  ctx.fillText(`Market Snapshot 4-Pack (${asofDate} KST)`, 30, 52);

  const gap = 20;
  const panelWidth = (width - 30 * 2 - gap) / 2;
  const panelHeight = (height - 90 - 30 - gap) / 2;

  drawPanel(ctx, panels[0], 30, 90, panelWidth, panelHeight);
  drawPanel(ctx, panels[1], 30 + panelWidth + gap, 90, panelWidth, panelHeight);
  drawPanel(ctx, panels[2], 30, 90 + panelHeight + gap, panelWidth, panelHeight);
  drawPanel(ctx, panels[3], 30 + panelWidth + gap, 90 + panelHeight + gap, panelWidth, panelHeight);

  ctx.fillStyle = "#8094c2";
  ctx.font = "12px Arial";
  ctx.fillText("Generated by SBUSIM", width - 180, height - 12);

  return canvas.toBuffer("image/png");
}

export async function uploadChartImage(args: {
  supabase: SupabaseClient;
  buffer: Buffer;
  asofDate: string;
  chartKind: "daily_snapshot_4pack" | "single_instrument_7d";
  bucket?: string;
}) {
  const bucket = args.bucket ?? "social-assets";
  const filePath = `charts/${args.asofDate}/${args.chartKind}-${Date.now()}.png`;

  const { error: uploadError } = await args.supabase.storage
    .from(bucket)
    .upload(filePath, args.buffer, {
      contentType: "image/png",
      upsert: true,
    });

  if (uploadError) {
    throw new Error(`chart upload failed: ${uploadError.message}`);
  }

  const { data: publicData } = args.supabase.storage.from(bucket).getPublicUrl(filePath);
  const publicUrl = publicData?.publicUrl;
  if (publicUrl) {
    return { url: publicUrl, path: filePath };
  }

  const { data: signedData, error: signedError } = await args.supabase.storage
    .from(bucket)
    .createSignedUrl(filePath, 60 * 60 * 24 * 14);
  if (signedError || !signedData?.signedUrl) {
    throw new Error(`chart signed URL failed: ${signedError?.message ?? "missing signed url"}`);
  }

  return { url: signedData.signedUrl, path: filePath };
}
